create database kampusBD;
use kampusBD;


CREATE TABLE DOSEN1 (
    ID_DOSEN INT PRIMARY KEY,
    NAMA_DOSEN VARCHAR(100), -- Atribut untuk nama lengkap dosen
    EMAIL_DOSEN VARCHAR(100)
);


CREATE TABLE KULIAH1 (
    ID_KULIAH INT PRIMARY KEY,
    NAMA_KULIAH VARCHAR(100),
    SKS INT,
    ID_DOSEN INT,
    FOREIGN KEY (ID_DOSEN) REFERENCES DOSEN(ID_DOSEN)
);


CREATE TABLE DOSEN (
    ID_DOSEN INT PRIMARY KEY,
    NAMA_DEPAN_DOSEN VARCHAR(50),
    NAMA_BELAKANG_DOSEN VARCHAR(50),
    NAMA_DOSEN VARCHAR(101) GENERATED ALWAYS AS (CONCAT(NAMA_DEPAN_DOSEN, ' ', NAMA_BELAKANG_DOSEN)) VIRTUAL,
    EMAIL_DOSEN VARCHAR(100)
);


CREATE TABLE KULIAH (
    ID_KULIAH INT PRIMARY KEY,
    NAMA_KULIAH VARCHAR(100),
    NO_DEPT INT,
    ID_DOSEN INT,
    FOREIGN KEY (ID_DOSEN) REFERENCES DOSEN(ID_DOSEN)
);

CREATE TABLE Departemen (
    KodeDept INT PRIMARY KEY,
    NamaDept VARCHAR(100) NOT NULL
);

CREATE TABLE Pegawai (
    KodePegawai INT PRIMARY KEY,
    NamaPegawai VARCHAR(100) NOT NULL,
    KodeDept INT NOT NULL,
    KodePemimpin INT, 
    FOREIGN KEY (KodeDept) REFERENCES Departemen(KodeDept),
    FOREIGN KEY (KodePemimpin) REFERENCES Pegawai(KodePegawai)
);

SELECT 
    P1.KodePegawai,
    P1.NamaPegawai,
    P1.KodeDept,
    D.NamaDept,
    P1.KodePemimpin,
    P2.NamaPegawai AS NamaPemimpin
FROM 
    Pegawai P1
LEFT JOIN 
    Pegawai P2 ON P1.KodePemimpin = P2.KodePegawai
LEFT JOIN 
    Departemen D ON P1.KodeDept = D.KodeDept;

CREATE TABLE DEPARTEMEN1(
NO_DEPT CHAR(15) NOT NULL,
NAMA_DEPT CHAR(35) NOT NULL,
PRIMARY KEY (NO_DEPT));

CREATE TABLE PEGAWAI1(
NO_PEG CHAR(6) PRIMARY KEY NOT NULL,
NAMA_PEGAWAI CHAR(40) NOT NULL,
NO_HP CHAR(15) NOT NULL,
NO_DEPT CHAR(15) NOT NULL,
FOREIGN KEY (NO_DEPT) REFERENCES DEPARTEMEN1 (NO_DEPT)
ON DELETE RESTRICT ON UPDATE CASCADE);



